name: image_counter_app
description: A Flutter app with image gallery and counter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^6.1.1
  video_player: ^2.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/
